{% set version = "1.3.6" %}

package:
    name: mongoquery
    version: {{ version }}

source:
    url: https://github.com/kapouille/mongoquery/archive/{{ version }}.tar.gz
    fn: mongoquery-{{ version }}.tar.gz
    sha256: 27473381244d06c2ff0f6810d84bbec6d2b46f9c1b1f814e3333bb6bfe193ea6

build:
    noarch: python
    number: 0
    script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
    build:
        - pip
        - python
    run:
        - python
        - six

test:
    imports:
        - mongoquery

about:
    home: https://github.com/kapouille/mongoquery
    license: Public Domain
    summary: >
        A utility library that provides a MongoDB-like query
        language for querying python collections. It's mainly
        intended to parse objects structured as fundamental types in
        a similar fashion to what is produced by JSON or YAML
        parsers.

extra:
    recipe-maintainers:
        - ericdill
        - kapouille
        - licode
        - tacaswell
        - CJ-Wright
