appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
travis:
  secure:
    BINSTAR_TOKEN: mGZCy6HTFsZfzCXSwiIYRpN27IQKB6s5Gatf17cDipJQ9qEECmLPYyUS7bbrnL7ykA0fquh5QZ2eDPlLLZRyIUELiLr0CuUFAHb7vWwHWTSvr0LwshlFeglLaWzKVtFHUWzob7Ukc6vXBiiXfJ61NOsBtaxR1nV9imMzWZC0db4IHKOebSCVS4qmPnHPB5BrUYWQCuUWh8g9Ol8ibbWTFmOBQ8idK+fbda2dfd8fObsxSL1JjBHY9G0zuc4KqPoNcLFSXDgv1Z27+rkpblk1Lk+1wQDl5mfqo+JSoduavfewqy5eyLVLPH33R369j9v8kPksekwXhXuERlA76WZ0RUcPLAR3AuFiwiXvG+W0nVje/4ztKHJk8kjHPj9P8kPi/RA4OTVw0eGqahJTgVl0ZztTBgVN9DMgs3mt0KkwGbvN3pRUzxeqoONO1lqRYLNiU+YrA3oyI8nL8Q613BEH8kdH3vj/apHbK0+V9ajhnYyyM5O0MrEaQO5OJMWrAvpZOt8Ng9Z/l8YErVRiCo3yJgsDp9t0VYKNNum2jZW7jqLnnvPDIf2j1KJgnmCYoLwAkKhOQNy8MVbOLA/e2LVcHKLXzs5PkOhCdfMnXFnWkAU2jtUp9+GEQplRNN2TZHyoBcHCwAm/alOGuiC+2UMKJ3E2BB+2jJKm8pG3Eyeb8u4=
